"""create category field options table

Revision ID: 070a2816179e
Revises: 74c3cd6f386b
Create Date: 2026-08-05 07:10:48.482262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070a2816179e'
down_revision: Union[str, Sequence[str], None] = '74c3cd6f386b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_field_options',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_category_field_options_sort_order'),
    sa.ForeignKeyConstraint(['field_id'], ['category_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'value', name='uq_category_field_options_field_value')
    )
    op.create_index('ix_category_field_options_field_id', 'category_field_options', ['field_id'], unique=False)
    op.create_index('ix_category_field_options_field_sort_order', 'category_field_options', ['field_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_category_field_options_public_id'), 'category_field_options', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_field_options_public_id'), table_name='category_field_options')
    op.drop_index('ix_category_field_options_field_sort_order', table_name='category_field_options')
    op.drop_index('ix_category_field_options_field_id', table_name='category_field_options')
    op.drop_table('category_field_options')
    # ### end Alembic commands ###
