"""add item image caption

Revision ID: 21f779d6e45f
Revises: a7dc10c53609
Create Date: 2026-08-06 05:25:16.023230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f779d6e45f'
down_revision: Union[str, Sequence[str], None] = 'a7dc10c53609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_images', sa.Column('caption', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_images', 'caption')
    # ### end Alembic commands ###
