"""create category metadata providers table

Revision ID: 56260a831c30
Revises: b4e3aa89e86e
Create Date: 2026-08-04 14:52:06.872229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56260a831c30'
down_revision: Union[str, Sequence[str], None] = 'b4e3aa89e86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_metadata_providers',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('stop_on_match', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('configuration', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority >= 0', name='ck_category_metadata_providers_priority'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['metadata_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'provider_id', name='uq_category_metadata_providers_category_provider')
    )
    op.create_index('ix_category_metadata_providers_category_priority', 'category_metadata_providers', ['category_id', 'priority'], unique=False)
    op.create_index('ix_category_metadata_providers_provider_id', 'category_metadata_providers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_category_metadata_providers_public_id'), 'category_metadata_providers', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_metadata_providers_public_id'), table_name='category_metadata_providers')
    op.drop_index('ix_category_metadata_providers_provider_id', table_name='category_metadata_providers')
    op.drop_index('ix_category_metadata_providers_category_priority', table_name='category_metadata_providers')
    op.drop_table('category_metadata_providers')
    # ### end Alembic commands ###
