"""create item storage assignments table

Revision ID: 63f891d85ff1
Revises: d37d7ea6d23a
Create Date: 2026-08-05 10:06:30.472161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f891d85ff1'
down_revision: Union[str, Sequence[str], None] = 'd37d7ea6d23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_storage_assignments',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('moved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('movement_reason', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['collection_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_storage_assignments_item_history', 'item_storage_assignments', ['item_id', 'assigned_at'], unique=False)
    op.create_index('ix_item_storage_assignments_item_id', 'item_storage_assignments', ['item_id'], unique=False)
    op.create_index('ix_item_storage_assignments_location_active', 'item_storage_assignments', ['storage_location_id', 'is_active'], unique=False)
    op.create_index('ix_item_storage_assignments_moved_by_user_id', 'item_storage_assignments', ['moved_by_user_id'], unique=False)
    op.create_index(op.f('ix_item_storage_assignments_public_id'), 'item_storage_assignments', ['public_id'], unique=True)
    op.create_index('ix_item_storage_assignments_storage_location_id', 'item_storage_assignments', ['storage_location_id'], unique=False)
    op.create_index('uq_item_storage_assignments_active_item', 'item_storage_assignments', ['item_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_item_storage_assignments_active_item', table_name='item_storage_assignments', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_item_storage_assignments_storage_location_id', table_name='item_storage_assignments')
    op.drop_index(op.f('ix_item_storage_assignments_public_id'), table_name='item_storage_assignments')
    op.drop_index('ix_item_storage_assignments_moved_by_user_id', table_name='item_storage_assignments')
    op.drop_index('ix_item_storage_assignments_location_active', table_name='item_storage_assignments')
    op.drop_index('ix_item_storage_assignments_item_id', table_name='item_storage_assignments')
    op.drop_index('ix_item_storage_assignments_item_history', table_name='item_storage_assignments')
    op.drop_table('item_storage_assignments')
    # ### end Alembic commands ###
