"""create item field values table

Revision ID: 6d1b435d3a32
Revises: ac6409a91e3f
Create Date: 2026-08-05 07:27:19.493856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1b435d3a32'
down_revision: Union[str, Sequence[str], None] = 'ac6409a91e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_field_values',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_decimal', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                CASE WHEN value_text IS NOT NULL THEN 1 ELSE 0 END\n                +\n                CASE WHEN value_integer IS NOT NULL THEN 1 ELSE 0 END\n                +\n                CASE WHEN value_decimal IS NOT NULL THEN 1 ELSE 0 END\n                +\n                CASE WHEN value_boolean IS NOT NULL THEN 1 ELSE 0 END\n                +\n                CASE WHEN value_date IS NOT NULL THEN 1 ELSE 0 END\n                +\n                CASE WHEN value_json IS NOT NULL THEN 1 ELSE 0 END\n            ) <= 1\n            ', name='ck_item_field_values_single_value'),
    sa.ForeignKeyConstraint(['field_id'], ['category_fields.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['collection_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'field_id', name='uq_item_field_values_item_field')
    )
    op.create_index('ix_item_field_values_field_date', 'item_field_values', ['field_id', 'value_date'], unique=False)
    op.create_index('ix_item_field_values_field_decimal', 'item_field_values', ['field_id', 'value_decimal'], unique=False)
    op.create_index('ix_item_field_values_field_id', 'item_field_values', ['field_id'], unique=False)
    op.create_index('ix_item_field_values_field_integer', 'item_field_values', ['field_id', 'value_integer'], unique=False)
    op.create_index('ix_item_field_values_field_text', 'item_field_values', ['field_id', 'value_text'], unique=False)
    op.create_index('ix_item_field_values_item_id', 'item_field_values', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_field_values_public_id'), 'item_field_values', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_field_values_public_id'), table_name='item_field_values')
    op.drop_index('ix_item_field_values_item_id', table_name='item_field_values')
    op.drop_index('ix_item_field_values_field_text', table_name='item_field_values')
    op.drop_index('ix_item_field_values_field_integer', table_name='item_field_values')
    op.drop_index('ix_item_field_values_field_id', table_name='item_field_values')
    op.drop_index('ix_item_field_values_field_decimal', table_name='item_field_values')
    op.drop_index('ix_item_field_values_field_date', table_name='item_field_values')
    op.drop_table('item_field_values')
    # ### end Alembic commands ###
