"""create category fields table

Revision ID: 74c3cd6f386b
Revises: 41d4cff9c0e2
Create Date: 2026-08-05 07:04:26.555947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c3cd6f386b'
down_revision: Union[str, Sequence[str], None] = '41d4cff9c0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_fields',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_visible_in_list', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('validation_rules', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('default_value', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            field_type IN (\n                'text',\n                'long_text',\n                'integer',\n                'decimal',\n                'boolean',\n                'date',\n                'year',\n                'url',\n                'email',\n                'single_select',\n                'multi_select',\n                'barcode',\n                'image',\n                'file'\n            )\n            ", name='ck_category_fields_type'),
    sa.CheckConstraint('sort_order >= 0', name='ck_category_fields_sort_order'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'field_key', name='uq_category_fields_category_key')
    )
    op.create_index('ix_category_fields_category_id', 'category_fields', ['category_id'], unique=False)
    op.create_index('ix_category_fields_category_sort_order', 'category_fields', ['category_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_category_fields_public_id'), 'category_fields', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_fields_public_id'), table_name='category_fields')
    op.drop_index('ix_category_fields_category_sort_order', table_name='category_fields')
    op.drop_index('ix_category_fields_category_id', table_name='category_fields')
    op.drop_table('category_fields')
    # ### end Alembic commands ###
