"""create legacy book migrations table

Revision ID: 955a139941e8
Revises: e334d5291a18
Create Date: 2026-08-05 09:48:27.766238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955a139941e8'
down_revision: Union[str, Sequence[str], None] = 'e334d5291a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_book_migrations',
    sa.Column('legacy_book_id', sa.Integer(), nullable=False),
    sa.Column('collection_item_id', sa.Integer(), nullable=True),
    sa.Column('legacy_location_id', sa.Integer(), nullable=True),
    sa.Column('legacy_isbn', sa.String(length=255), nullable=True),
    sa.Column('legacy_borrowed_to', sa.Text(), nullable=True),
    sa.Column('legacy_room', sa.String(length=100), nullable=True),
    sa.Column('legacy_shelf', sa.String(length=100), nullable=True),
    sa.Column('legacy_slot', sa.Integer(), nullable=True),
    sa.Column('migration_status', sa.String(length=30), nullable=False),
    sa.Column('migration_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            migration_status IN (\n                'pending',\n                'migrated',\n                'warning',\n                'error'\n            )\n            ", name='ck_legacy_book_migrations_status'),
    sa.ForeignKeyConstraint(['collection_item_id'], ['collection_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_item_id', name='uq_legacy_book_migrations_collection_item_id'),
    sa.UniqueConstraint('legacy_book_id', name='uq_legacy_book_migrations_legacy_book_id')
    )
    op.create_index('ix_legacy_book_migrations_legacy_location_id', 'legacy_book_migrations', ['legacy_location_id'], unique=False)
    op.create_index(op.f('ix_legacy_book_migrations_public_id'), 'legacy_book_migrations', ['public_id'], unique=True)
    op.create_index('ix_legacy_book_migrations_status', 'legacy_book_migrations', ['migration_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legacy_book_migrations_status', table_name='legacy_book_migrations')
    op.drop_index(op.f('ix_legacy_book_migrations_public_id'), table_name='legacy_book_migrations')
    op.drop_index('ix_legacy_book_migrations_legacy_location_id', table_name='legacy_book_migrations')
    op.drop_table('legacy_book_migrations')
    # ### end Alembic commands ###
