"""add item images

Revision ID: a7dc10c53609
Revises: b3b2ebcabd8a
Create Date: 2026-08-06 04:48:32.357447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dc10c53609'
down_revision: Union[str, Sequence[str], None] = 'b3b2ebcabd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_images',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size >= 0', name='ck_item_images_file_size_nonnegative'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='ck_item_images_height_positive'),
    sa.CheckConstraint('sort_order >= 0', name='ck_item_images_sort_order_nonnegative'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_item_images_width_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['collection_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_images_item_active', 'item_images', ['item_id', 'is_active'], unique=False)
    op.create_index('ix_item_images_item_id', 'item_images', ['item_id'], unique=False)
    op.create_index('ix_item_images_item_primary', 'item_images', ['item_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_item_images_public_id'), 'item_images', ['public_id'], unique=True)
    op.create_index('ix_item_images_stored_filename', 'item_images', ['stored_filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_images_stored_filename', table_name='item_images')
    op.drop_index(op.f('ix_item_images_public_id'), table_name='item_images')
    op.drop_index('ix_item_images_item_primary', table_name='item_images')
    op.drop_index('ix_item_images_item_id', table_name='item_images')
    op.drop_index('ix_item_images_item_active', table_name='item_images')
    op.drop_table('item_images')
    # ### end Alembic commands ###
