"""create collection items table

Revision ID: ac6409a91e3f
Revises: c414f2afdc64
Create Date: 2026-08-05 07:21:35.250357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6409a91e3f'
down_revision: Union[str, Sequence[str], None] = 'c414f2afdc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'active',\n                'loaned',\n                'archived',\n                'missing',\n                'disposed'\n            )\n            ", name='ck_collection_items_status'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_items_category_id', 'collection_items', ['category_id'], unique=False)
    op.create_index('ix_collection_items_created_by_user_id', 'collection_items', ['created_by_user_id'], unique=False)
    op.create_index('ix_collection_items_household_category', 'collection_items', ['household_id', 'category_id'], unique=False)
    op.create_index('ix_collection_items_household_status', 'collection_items', ['household_id', 'status'], unique=False)
    op.create_index(op.f('ix_collection_items_public_id'), 'collection_items', ['public_id'], unique=True)
    op.create_index('ix_collection_items_updated_by_user_id', 'collection_items', ['updated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collection_items_updated_by_user_id', table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_public_id'), table_name='collection_items')
    op.drop_index('ix_collection_items_household_status', table_name='collection_items')
    op.drop_index('ix_collection_items_household_category', table_name='collection_items')
    op.drop_index('ix_collection_items_created_by_user_id', table_name='collection_items')
    op.drop_index('ix_collection_items_category_id', table_name='collection_items')
    op.drop_table('collection_items')
    # ### end Alembic commands ###
