"""create metadata providers table

Revision ID: b197a428a2c4
Revises: f3b49c9ce069
Create Date: 2026-08-04 14:42:25.315976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b197a428a2c4'
down_revision: Union[str, Sequence[str], None] = 'f3b49c9ce069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_providers',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('plugin_key', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_barcode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_text_search', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_images', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('configuration_schema', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            provider_type IN (\n                'remote_api',\n                'web_lookup',\n                'local_database',\n                'manual',\n                'import'\n            )\n            ", name='ck_metadata_providers_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_providers_public_id'), 'metadata_providers', ['public_id'], unique=True)
    op.create_index('uq_metadata_providers_code', 'metadata_providers', ['code'], unique=True)
    op.create_index('uq_metadata_providers_plugin_key', 'metadata_providers', ['plugin_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_metadata_providers_plugin_key', table_name='metadata_providers')
    op.drop_index('uq_metadata_providers_code', table_name='metadata_providers')
    op.drop_index(op.f('ix_metadata_providers_public_id'), table_name='metadata_providers')
    op.drop_table('metadata_providers')
    # ### end Alembic commands ###
