"""create storage locations table

Revision ID: d37d7ea6d23a
Revises: 955a139941e8
Create Date: 2026-08-05 09:51:22.805809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37d7ea6d23a'
down_revision: Union[str, Sequence[str], None] = '955a139941e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_locations',
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.String(length=30), server_default=sa.text("'other'"), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            location_type IN (\n                'room',\n                'shelf',\n                'cabinet',\n                'drawer',\n                'box',\n                'slot',\n                'area',\n                'other'\n            )\n            ", name='ck_storage_locations_type'),
    sa.CheckConstraint('sort_order >= 0', name='ck_storage_locations_sort_order'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_locations_household_id', 'storage_locations', ['household_id'], unique=False)
    op.create_index('ix_storage_locations_household_parent', 'storage_locations', ['household_id', 'parent_id'], unique=False)
    op.create_index('ix_storage_locations_parent_id', 'storage_locations', ['parent_id'], unique=False)
    op.create_index(
        'uq_storage_locations_root_slug',
        'storage_locations',
        ['household_id', 'slug'],
        unique=True,
        postgresql_where=sa.text('parent_id IS NULL'),
    )

    op.create_index(
        'uq_storage_locations_child_slug',
        'storage_locations',
        ['household_id', 'parent_id', 'slug'],
        unique=True,
        postgresql_where=sa.text('parent_id IS NOT NULL'),
    )
    op.create_index(op.f('ix_storage_locations_public_id'), 'storage_locations', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_storage_locations_child_slug',
        table_name='storage_locations',
        postgresql_where=sa.text('parent_id IS NOT NULL'),
    )

    op.drop_index(
        'uq_storage_locations_root_slug',
        table_name='storage_locations',
        postgresql_where=sa.text('parent_id IS NULL'),
    )
    op.drop_index(op.f('ix_storage_locations_public_id'), table_name='storage_locations')
    op.drop_index('ix_storage_locations_parent_id', table_name='storage_locations')
    op.drop_index('ix_storage_locations_household_parent', table_name='storage_locations')
    op.drop_index('ix_storage_locations_household_id', table_name='storage_locations')
    op.drop_table('storage_locations')
    # ### end Alembic commands ###
