"""create item identifiers table

Revision ID: e334d5291a18
Revises: 6d1b435d3a32
Create Date: 2026-08-05 07:32:00.667500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e334d5291a18'
down_revision: Union[str, Sequence[str], None] = '6d1b435d3a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_identifiers',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.Column('provider_code', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            identifier_type IN (\n                'isbn10',\n                'isbn13',\n                'ean8',\n                'ean13',\n                'upc',\n                'issn',\n                'catalog_number',\n                'provider_external_id',\n                'custom',\n                'qr',\n                'rfid',\n                'nfc'\n            )\n            ", name='ck_item_identifiers_type'),
    sa.ForeignKeyConstraint(['item_id'], ['collection_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'identifier_type', 'identifier_value', name='uq_item_identifiers_item_type_value')
    )
    op.create_index('ix_item_identifiers_item_id', 'item_identifiers', ['item_id'], unique=False)
    op.create_index('ix_item_identifiers_provider_code', 'item_identifiers', ['provider_code'], unique=False)
    op.create_index(op.f('ix_item_identifiers_public_id'), 'item_identifiers', ['public_id'], unique=True)
    op.create_index('ix_item_identifiers_type_value', 'item_identifiers', ['identifier_type', 'identifier_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_identifiers_type_value', table_name='item_identifiers')
    op.drop_index(op.f('ix_item_identifiers_public_id'), table_name='item_identifiers')
    op.drop_index('ix_item_identifiers_provider_code', table_name='item_identifiers')
    op.drop_index('ix_item_identifiers_item_id', table_name='item_identifiers')
    op.drop_table('item_identifiers')
    # ### end Alembic commands ###
