"""add category storage location rules

Revision ID: f85a1e67532a
Revises: 6ba44e6e82e8
Create Date: 2026-08-08 15:27:07.256796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85a1e67532a'
down_revision: Union[str, Sequence[str], None] = '6ba44e6e82e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_storage_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('include_descendants', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'category_id', 'storage_location_id', name='uq_category_storage_locations_household_category_location')
    )
    op.create_index('ix_category_storage_locations_category_id', 'category_storage_locations', ['category_id'], unique=False)
    op.create_index('ix_category_storage_locations_household_category', 'category_storage_locations', ['household_id', 'category_id'], unique=False)
    op.create_index('ix_category_storage_locations_household_id', 'category_storage_locations', ['household_id'], unique=False)
    op.create_index('ix_category_storage_locations_storage_location_id', 'category_storage_locations', ['storage_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_storage_locations_storage_location_id', table_name='category_storage_locations')
    op.drop_index('ix_category_storage_locations_household_id', table_name='category_storage_locations')
    op.drop_index('ix_category_storage_locations_household_category', table_name='category_storage_locations')
    op.drop_index('ix_category_storage_locations_category_id', table_name='category_storage_locations')
    op.drop_table('category_storage_locations')
    # ### end Alembic commands ###
