from app.services.auth import (
    authenticate_user,
    get_user_by_email,
    normalize_email,
)
from app.services.collection_items import (
    CollectionItemCreateInput,
    CollectionItemUpdateInput,
    update_collection_item,
    IdentifierInput,
    create_collection_item,
)
from app.services.legacy_books import (
    LegacyBookSource,
    NormalizedLegacyIdentifier,
    PreparedLegacyBook,
    normalize_legacy_identifier,
    normalize_publish_year,
    prepare_legacy_book,
    LegacyBookMigrationResult,
    LegacyLocationSource,
    migrate_legacy_book,
    LegacyBookBatchError,
    LegacyBookBatchResult,
    migrate_legacy_books_batch,
    load_legacy_book_sources_from_database,
)


from app.services.books_read import (
    BookReadPage,
    BookReadRecord,
    get_book_by_legacy_id,
    list_books,
    list_latest_books,
    move_book_to_storage_location,
    resolve_storage_location_from_legacy_id,
    soft_delete_book_by_legacy_id,
    update_collection_item_title,
    update_primary_identifier,
    update_book_metadata_fields,
    update_book_borrow_state,
    update_book_by_legacy_id,
)


__all__ = [
    "authenticate_user",
    "get_user_by_email",
    "normalize_email",
    "CollectionItemCreateInput",
    "CollectionItemUpdateInput",
    "update_collection_item",
    "IdentifierInput",
    "create_collection_item",
    "LegacyBookSource",
    "NormalizedLegacyIdentifier",
    "PreparedLegacyBook",
    "normalize_legacy_identifier",
    "normalize_publish_year",
    "prepare_legacy_book",
    "LegacyBookMigrationResult",
    "LegacyLocationSource",
    "migrate_legacy_book",
    "LegacyBookBatchError",
    "LegacyBookBatchResult",
    "migrate_legacy_books_batch",
    "load_legacy_book_sources_from_database",
    "BookReadPage",
    "BookReadRecord",
    "get_book_by_legacy_id",
    "list_books",
    "list_latest_books",
    "move_book_to_storage_location",
    "resolve_storage_location_from_legacy_id",
    "soft_delete_book_by_legacy_id",
    "update_collection_item_title",
    "update_book_metadata_fields",
    "update_primary_identifier",
    "update_book_borrow_state",
    "update_book_by_legacy_id",
]
